services:
  - type: web
    name: flask-mat-dashboard
    plan: starter
    env: python
    region: singapore  
    rootDir: Dashboard-Interface
    buildCommand: "Dashboard-Interface/build.sh"
    startCommand: "gunicorn run:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: FALSE
